### ISSUE TITLE
go get tidb version

### ISSUE THREAD

**Issue by photoszzt** [tikv/client-go#4] opened 2019-02-22 16:56 UTC
I'm not sure whether I should file here or in docs. But I follow the document to start using the go client
```bash
go get github.com/pingcap/tidb@master
go build
```
go get downloads tidb@v2.0.11+incompatible. The during go build, it gives out this error:
/tidb@v2.0.11+incompatible/store/tikv/kv.go:28:2: unknown import path "github.com/pingcap/pd/pd-client": cannot find module providing package github.com/pingcap/pd/pd-client

I fix this problem by reinitialize the project with 
```bash
go get github.com/pingcap/tidb@v2.1.4
```

**Comment by rleungx** [comment] 2019-02-23 07:29
@photoszzt Thanks for your feedback!
I tried to reproduce this problem but it failed. Can you paste your `go.sum` related to `pd` and `tidb`? And what is your go version?

**Comment by photoszzt** [comment] 2019-02-23 16:26
@rleungx my go version is go version go1.11.5 linux/amd64
The go.sum that relates to pd and tidb are follows:

github.com/pingcap/pd v2.1.0-rc.4+incompatible/go.mod h1:nD3+EoYes4+aNNODO99ES59V83MZSI+dFbhyr667a0E=
github.com/pingcap/tidb v0.0.0-20190222104944-266ff4b6f37e h1:xQs5Ok4Izhg9kyoJDOvZpEUIo/4xawOAM0KErQFIe0A=
github.com/pingcap/tidb v0.0.0-20190222104944-266ff4b6f37e/go.mod h1:TJqjPfIfyYi+n93XFa46sxy1ckox9BZh++b4RPorK3U=
github.com/pingcap/tidb v2.0.11+incompatible h1:Shz+ry1DzQNsPk1QAejnM+5tgjbwZuzPnIER5aCjQ6c=
github.com/pingcap/tidb v2.0.11+incompatible/go.mod h1:I8C6jrPINP2rrVunTRd7C9fRRhQrtR43S1/CL5ix/yQ=

**Comment by rleungx** [comment] 2019-02-27 09:38
@photoszzt Sorry for the late reply. This indeed a bug when using the transaction API as the documentation says. I am trying to find out why it happens.

**Comment by rleungx** [comment] 2019-02-28 12:35
@photoszzt Can you try to replace`"github.com/pingcap/tidb/terror"` with `"github.com/pingcap/parser/terror"` to check if it can work?

**Comment by photoszzt** [comment] 2019-02-28 16:53
@rleungx Unfortunately, it still not fix it. This time I can compile but the application failed to function. I keep geting this error:

ERRO[0000] batchRecvLoop error when receive: rpc error: code = Unimplemented desc =  
INFO[0000] batchRecvLoop re-create streaming success    

But with the original terror, there's no such problem.

**Comment by rleungx** [comment] 2019-03-01 04:10
@photoszzt Which version do you use? Since `
go get github.com/pingcap/tidb@master` use the master branch, can you try to use PD and TiKV with  the master branch?

**Comment by photoszzt** [comment] 2019-03-01 05:42
@rleungx both tikv and pd are on 2.1.4. I will try the master version.

**Comment by photoszzt** [comment] 2019-03-03 02:33
@rleungx I try the version on master. It works. I think it's better to match the release version for the client API unless people are expected to compile code from master.

**Comment by siddontang** [comment] 2019-03-03 06:04
Thanks @photoszzt 

Maybe it is better to check all versions at first, we will consider this in tikv/client-go.

**Comment by kamijin-fanta** [comment] 2019-04-16 07:02
I used tikv `v3.0.0-beta.1`. "batchRecvLoop error" was not output.

**Comment by rleungx** [comment] 2019-04-17 07:19
@kamijin-fanta Thanks for your feedback!
Can you explain more about your operations? Have you followed the instruction [here](https://github.com/pingcap/docs/blob/master/tikv/go-client-api.md)? I am not very clear about your question.

**Comment by kamijin-fanta** [comment] 2019-04-17 07:30
@rleungx tikv/go-client calls `BatchCommands` RPC. This was implemented for the first time in TiKV version `3.0.0-beta.1`. I launched TiKV with docker, followed the guide and created a client with `tikv.NewRawKVClient`.

Caller:
https://github.com/tikv/client-go/blob/2130e26d4f3a98347108373827d14c1f5a3c595c/rpc/client.go#L113

 Implementation:
https://github.com/tikv/tikv/blob/v3.0.0-beta.1/src/server/service/kv.rs#L848

And I was success to connect to the old version server by executing `config.MaxBatchSize = 0`.

**Comment by rleungx** [comment] 2019-04-19 05:36
@kamijin-fanta To make things more clear, you followed the instruction and run the example of the raw client. But it failed with outputting nothing, am I right?

**Comment by siddontang** [comment] 2019-04-22 00:28
seem if we disable batch message with `config.MaxBatchSize = 0`, we can connect to the 2.1 version of TiKV. 

Please verify it @rleungx

**Comment by disksing** [comment] 2019-04-22 03:46
@kamijin-fanta You can try the latest master version. Batch messages disabled by default.

**Comment by disksing** [comment] 2021-06-20 17:03
Now we can use v2 version. Closing this issue.

**Closed by disksing** 2021-06-20 17:03 UTC
Labels: bug
