### ISSUE TITLE
Using tikv client-go@v2.0.0-alpha has some error

### ISSUE THREAD

**Issue by 1026237416** [tikv/client-go#284] opened 2021-08-24 13:11 UTC
![image](https://user-images.githubusercontent.com/6825312/130616632-2be122da-07ec-4add-8a0e-468d2a24d32c.png)

**Comment by disksing** [comment] 2021-08-25 07:43
Hi @1026237416 , do you import etcd in your project?

**Comment by cmsax** [comment] 2021-08-31 02:47
I have the same issue when using `/v2/tikv`, there is an compiler error:

```
../../../../go/pkg/mod/github.com/tikv/client-go/v2@v2.0.0-alpha/tikv/txn.go:47:2: missing go.sum entry for module providing package github.com/dgryski/go-farm (imported by github.com/tikv/client-go/v2/tikv); to add:
        go get github.com/tikv/client-go/v2/tikv@v2.0.0-alpha
```

after ran `go get`, there was another error:

```
go get github.com/tikv/client-go/v2/tikv@v2.0.0-alpha
# go.etcd.io/etcd/clientv3/balancer/picker
../../../../go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/clientv3/balancer/picker/err.go:25:9: cannot use &errPicker{...} (type *errPicker) as type Picker in return argument:
        *errPicker does not implement Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
../../../../go/pkg/mod/go.etcd.io/etcd@v0.5.0-alpha.5.0.20200824191128-ae9734ed278b/clientv3/balancer/picker/roundrobin_balanced.go:33:9: cannot use &rrBalanced{...} (type *rrBalanced) as type Picker in return argument:
        *rrBalanced does not implement Picker (wrong type for Pick method)
                have Pick(context.Context, balancer.PickInfo) (balancer.SubConn, func(balancer.DoneInfo), error)
                want Pick(balancer.PickInfo) (balancer.PickResult, error)
```

I've imported `trpc` which is a framework like `gRPC` and use `etcd` internally, following is my `go.mod`:

![image](https://user-images.githubusercontent.com/18530762/131433469-cdfb48eb-26f7-4c4b-92d3-50e59f5bb7d8.png)

**Comment by disksing** [comment] 2021-08-31 19:14
Yes, this should be a conflict issue caused by importing etcd multiple times. We may be able to fix this after we finish upgrading etcd upgrade before GA version.

Version 1.0 should be working, but it is missing some new features, such as 1pc and async commit.

**Comment by disksing** [comment] 2022-02-22 04:08
As etcd is upgraded now. I'll close it. If you still encounter errors, please reopen it or open new issue. Thanks!

**Closed by disksing** 2022-02-22 04:08 UTC
